[SERVICE]
    Flush           2
    Daemon          Off
    Log_Level       error

[INPUT]
    Name            cpu
    Tag             guest.cpu
    Interval_Sec    2

[OUTPUT]
    Name            stdout
    Match           *
    Format          json_lines
