-- ==============================================================================
-- CRMS Canonical Schema Normalizer (Lua Filter)
-- Description: Transforms raw plugin outputs into a backend-agnostic JSON structure.
--              Acts as the first line of defense against corrupted metric payloads.
-- ==============================================================================

function format_to_crms_schema(tag, timestamp, record)
    local new_record = {}
    
    -- 1. Identity Mapping
    -- Maps the injected environment variables to the resource schema.
    -- Fallbacks are provided, but the gateway should ultimately reject 'unknown' IDs.
    new_record["resource"] = {
        ["type"] = "instance",
        ["id"] = record["resource_id"] or "unknown_instance",
        ["project_id"] = record["project_id"] or "unknown_project"
    }

    -- 2. Metric Specification Initialization
    local metric_name = tag
    local metric_type = "gauge"
    local metric_unit = "unknown"
    local value = nil -- Initialized as nil (not 0.0) to detect missing fields.

    -- 3. Metric Routing and Value Extraction
    -- Depending on the tag, we extract the specific field generated by Fluent Bit.
    if tag == "guest.cpu" then
        metric_name = "guest.cpu.util"
        metric_unit = "percent"
        value = record["cpu_p"]
        
    elseif tag == "guest.memory" then
        metric_name = "guest.memory.used_percent"
        metric_unit = "percent"
        -- Calculates actual usage percentage.
        if record["Mem.total"] and record["Mem.used"] then
            value = (record["Mem.used"] / record["Mem.total"]) * 100
        end
        
    elseif tag == "guest.net" then
        metric_name = "guest.net.in.bytes"
        metric_type = "cumulative"
        metric_unit = "bytes"
        value = record["rx.bytes"]
        
    elseif tag == "guest.disk" then
        metric_name = "guest.disk.read.bytes"
        metric_type = "cumulative"
        metric_unit = "bytes"
        value = record["read_size"]
    end

    -- 4. [CRITICAL] Anti-Silent-Failure Mechanism
    -- If the expected field (e.g., 'cpu_p' or 'rx.bytes') is missing due to OS 
    # differences or plugin updates, 'value' remains nil.
    -- We MUST drop this record (-1) rather than sending a fake 0.0, 
    -- which would corrupt billing and capacity planning calculations.
    if value == nil then
        return -1, 0, 0
    end

    -- 5. Final Schema Construction
    new_record["metric"] = {
        ["name"] = metric_name,
        ["type"] = metric_type,
        ["unit"] = metric_unit
    }
    
    -- Extract seconds from the timestamp structure (Fluent Bit handles time as a table).
    local ts_sec = timestamp
    if type(timestamp) == "table" then
        ts_sec = timestamp["sec"]
    end

    new_record["measure"] = {
        ["timestamp"] = ts_sec,
        ["value"] = value
    }

    -- Return 1 indicates the record was successfully modified.
    return 1, timestamp, new_record
end